"""add user_videos table

Revision ID: 0f0565ecfab6
Revises: f3847a8219fc
Create Date: 2026-02-17 21:46:49.751656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0565ecfab6'
down_revision: Union[str, None] = 'f3847a8219fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='unique_user_video')
    )
    op.create_index(op.f('ix_user_videos_id'), 'user_videos', ['id'], unique=False)
    op.drop_index('idx_videos_language', table_name='videos')
    op.drop_index('idx_videos_youtube_id', table_name='videos')
    op.drop_constraint('videos_youtube_video_id_key', 'videos', type_='unique')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    op.create_index(op.f('ix_videos_language'), 'videos', ['language'], unique=False)
    op.create_index(op.f('ix_videos_youtube_video_id'), 'videos', ['youtube_video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_youtube_video_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_language'), table_name='videos')
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_unique_constraint('videos_youtube_video_id_key', 'videos', ['youtube_video_id'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_videos_youtube_id', 'videos', ['youtube_video_id'], unique=False)
    op.create_index('idx_videos_language', 'videos', ['language'], unique=False)
    op.drop_index(op.f('ix_user_videos_id'), table_name='user_videos')
    op.drop_table('user_videos')
    # ### end Alembic commands ###
