"""add_user_preferences_videos_and_translations

Revision ID: 232c89f1ff94
Revises: 98817fed44f3
Create Date: 2026-01-21 16:33:37.030212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '232c89f1ff94'
down_revision: Union[str, None] = '98817fed44f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add user preferences columns
    op.add_column('user_words', sa.Column('translation', sa.String(), nullable=True))
    op.add_column('user_words', sa.Column('native_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('native_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('learning_language', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('topics', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('users', sa.Column('level', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True, server_default='false'))
    
    # Create videos table
    op.create_table(
        'videos',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('youtube_video_id', sa.String(20), unique=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('url', sa.String(), nullable=False),
        sa.Column('thumbnail_url', sa.String(), nullable=True),
        sa.Column('language', sa.String(10), nullable=False),
        sa.Column('available_subtitles', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('topics', sa.ARRAY(sa.String()), nullable=True),
        sa.Column('difficulty_level', sa.String(20), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), onupdate=sa.func.now()),
    )
    
    # Create indexes for videos table
    op.create_index('idx_videos_youtube_id', 'videos', ['youtube_video_id'])
    op.create_index('idx_videos_language', 'videos', ['language'])
    op.create_index('idx_videos_topics', 'videos', ['topics'], postgresql_using='gin')
    
    op.drop_column('words', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop videos table and indexes
    op.drop_index('idx_videos_topics', 'videos')
    op.drop_index('idx_videos_language', 'videos')
    op.drop_index('idx_videos_youtube_id', 'videos')
    op.drop_table('videos')
    
    # Restore words.updated_at and remove user preferences
    op.add_column('words', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'level')
    op.drop_column('users', 'topics')
    op.drop_column('users', 'learning_language')
    op.drop_column('users', 'native_language')
    op.drop_column('user_words', 'native_language')
    op.drop_column('user_words', 'translation')
    # ### end Alembic commands ###
