"""add_email_verification_and_password_reset_fields

Revision ID: 96475209ca56
Revises: 0f0565ecfab6
Create Date: 2026-02-23 17:56:46.107798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96475209ca56'
down_revision: Union[str, None] = '0f0565ecfab6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Grandfather existing users — mark them all as verified so they aren't locked out
    op.execute("UPDATE users SET is_verified = true WHERE is_verified IS NULL")
    op.alter_column('users', 'is_verified', nullable=False, server_default=sa.false())


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_token_expires_at')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
